#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# Input example:
#
#  {"site_name": "mymoodle", "username": "admin", "password": "admin", "email": "admin@test.local"}


import json
import sys
import agent
import agent.tasks
import os

request = json.load(sys.stdin)

# Setup default values
site_name = request.get("site_name","Moodle")
username = request.get("username","admin")
password = request.get("password","admin")
email = request.get("email", "admin@example.org")

# Talk with agent using file descriptor.
# Setup configuration from user input.
agent.set_env("MOODLE_SITE_NAME", site_name)
agent.set_env("MOODLE_USERNAME", username)
agent.set_env("MOODLE_PASSWORD", password)
agent.set_env("MOODLE_EMAIL", email)

agent.set_env("MOODLE_DATABASE_USER", "bn_moodle")
agent.set_env("MOODLE_DATABASE_PASSWORD", "bitnami")
agent.set_env("MOODLE_DATABASE_NAME", "bitnami_moodle")

# DB

agent.set_env("ALLOW_EMPTY_PASSWORD", "yes")
agent.set_env("MARIADB_USER", "bn_moodle")
agent.set_env("MARIADB_PASSWORD", "bitnami")
agent.set_env("MARIADB_DATABASE", "bitnami_moodle")

# Traefik

# Setup default values
host = data.get("host")
h2hs = data.get("http2https", True)
le = data.get("lets_encrypt", True)

# Talk with agent using file descriptor.
# Setup configuration from user input.
agent.set_env("TRAEFIK_HOST", host)
agent.set_env("TRAEFIK_HTTP2HTTPS", h2hs)
agent.set_env("TRAEFIK_LETS_ENCRYPT", le)

# Make sure everything is saved inside the environment file
# just before starting systemd unit
agent.dump_env()

# TODO: do something with the request payload. For example configure a
# custom route in our web router. Here the path is hardcoded as
# 'moodle'.

# Configure Traefik to route "/moodle" path requests to the moodle service
response = agent.tasks.run(
    agent_id=agent.resolve_agent_id('traefik@node'),
    action='set-route',
    data={
        'instance': os.environ['MODULE_ID'],
        'url':  'http://127.0.0.1:' + os.environ["TCP_PORT"],
        'host': host,
        'http2https': h2hs,
        'lets_encrypt': le
    },
)

# Check if traefik configuration has been successfull
agent.assert_exp(response['exit_code'] == 0)
