#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e -o pipefail
exec 1>&2 # Redirect any output to the journal (stderr)

# Prepare an initialization script that restores the dump file
mkdir -vp initdb.d
mv -v moodle.sql initdb.d
#do the bash file to restore and exit once done
cat - >initdb.d/zz_moodle_restore.sh <<'EOS'
# Print additional information:
mariadb --version
# The script is sourced, override entrypoint args and exit:
exit 0
EOS

# once we exit we remove initdb.d
trap 'rm -rfv initdb.d/' EXIT

# we start a container to initiate a database and load the dump
# at the end of moodle_restore.sh the dump is loaded and 
# we exit the container
podman run \
  --rm \
  --interactive \
  --network=none \
  --volume=./initdb.d:/docker-entrypoint-initdb.d:z \
  --env ALLOW_EMPTY_PASSWORD=yes \
  --env MARIADB_USER=bn_moodle \
  --env MARIADB_PASSWORD=bitnami \
  --env MARIADB_DATABASE=bitnami_moodle \
  --env MARIADB_CHARACTER_SET=utf8mb4 \
  --env MARIADB_COLLATE=utf8mb4_unicode_ci \
  --volume mariadb-data:/bitnami/mariadb:z \
  --replace --name=restore_db \
  ${MARIADB_IMAGE}
